In [2]:
import numpy as np
import pandas as pd

In [35]:
data = np.array([[1,8,3],[9,2,7],[4,10,5]])
data

array([[ 1,  8,  3],
       [ 9,  2,  7],
       [ 4, 10,  5]])

In [36]:
print("Sum:",np.sum(data))
print("Mean:",np.mean(data))
print("Max:",np.max(data))
print("Min:",np.min(data))
print("Median:",np.median(data))
print("Sorted:",np.sort(data))

Sum: 49
Mean: 5.444444444444445
Max: 10
Min: 1
Median: 5.0
Sorted: [[ 1  3  8]
 [ 2  7  9]
 [ 4  5 10]]


In [44]:
data1 = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [62]:
#Concate (left to right)
data2 = np.concatenate((data,data1),axis=1)
print("Concatenate number arrays:",data2)

Concatenate number arrays: [[ 1  8  3  1  2  3]
 [ 9  2  7  4  5  6]
 [ 4 10  5  1  2  3]]


In [54]:
mystring = np.array(["Papaya","Apple","Mango","Banana"])
mystring

array(['Papaya', 'Apple', 'Mango', 'Banana'], dtype='<U6')

In [65]:
print("Appending:",np.append(mystring,["Guava","Grapes"]))
print("Alphabetical sorting:",np.sort(mystring))
print("Spliting fruits:",np.char.split("Apple Chiku Orange"))
print("Adding 1:",np.char.add(mystring,"-1"))
print("Inserting Orange at 0th indexing:",np.insert(mystring,0,"Orange"))

Appending: ['Papaya' 'Apple' 'Mango' 'Banana' 'Guava' 'Grapes']
Alphabetical sorting: ['Apple' 'Banana' 'Mango' 'Papaya']
Spliting fruits: ['Apple', 'Chiku', 'Orange']
Adding 1: ['Papaya-1' 'Apple-1' 'Mango-1' 'Banana-1']
Inserting Orange at 0th indexing: ['Orange' 'Papaya' 'Apple' 'Mango' 'Banana']
